Ability to ignore or succeed by config settings
jenkinsci/stashnotifier-plugin pull request #159
Opened 2017-05-10 16:13 UTC by lucamilanesio

Introduce two new configuration settings to allow to control the
Stash notification in case of build aborted or unstable:

- disableAbortAsFailure: do not notify anything if build is aborted
- considerUnstableAsSuccess: when build is finished with some failures,
  consider the stash notification as a success

2017-05-10 16:48 UTC, scaytrase commented
What about leaving builds blue (inprogress) in case if `disableAbortAsFailure` is set to true and build was aborted? I think that actually this flag should behave equally with `disableInprogressNotification`  since there is no way to 'undo' the build from the bitbucket server now. 

So if the inprogress is off - disable abort failure too. if it is enabled - mark it red upon abort. 

What do you think, @lucamilanesio ?

2017-05-10 16:58 UTC, scaytrase requested changes
I think we also miss some tests for new behavior

2017-05-10 16:58 UTC, scaytrase commented on src/main/java/org/jenkinsci/plugins/stashNotifier/StashNotifier.java
> +				(buildResult == Result.UNSTABLE && considerUnstableAsSuccess)) {
maybe additional `else if` branch? would be easier to read

2017-05-10 16:58 UTC, scaytrase commented on src/main/java/org/jenkinsci/plugins/stashNotifier/StashNotifier.java
> +			return true;
I think we miss logging here too,

2017-05-11 10:38 UTC, lucamilanesio commented
@scaytrase yes, if disableInprogressNotification is true, then aborted build shouldn't do anything. Let me fix that.

2017-05-11 15:04 UTC, lucamilanesio commented
@scaytrase I've applied the changes, including the extra tests. Let me know if you need me to add/change anything else. Thanks for your review.

2017-05-11 17:13 UTC, scaytrase requested changes
Two minor issues and one logic question left. Everything else is OK

2017-05-11 17:13 UTC, scaytrase commented on src/test/java/org/jenkinsci/plugins/stashNotifier/StashNotifierTest.java
> +    public void test_perform_build_step_abourted_without_notifying_stash() throws Exception {
Little typo in `abourted`

2017-05-11 17:13 UTC, scaytrase commented on src/main/java/org/jenkinsci/plugins/stashNotifier/StashNotifier.java
> +		} else if (buildResult == Result.ABORTED && (disableAbortAsFailures || disableInProgress)) {
Should this be `(disableAbortAsFailures && disableInProgress)` ? We should not allow the notifier to leave the build blue, so if we have not disable inprogress thus we cannot drop aborted without marking?

2017-05-11 17:13 UTC, scaytrase commented on src/main/java/org/jenkinsci/plugins/stashNotifier/StashNotifier.java
> +			boolean disableAbortAsFailures,
I think this should be `disableAbortAsFailure` in a single form

2017-05-12 09:58 UTC, lucamilanesio commented on src/test/java/org/jenkinsci/plugins/stashNotifier/StashNotifierTest.java
> +    public void test_perform_build_step_abourted_without_notifying_stash() throws Exception {
Oops, fixing it now :-)

2017-05-12 10:03 UTC, lucamilanesio commented on src/main/java/org/jenkinsci/plugins/stashNotifier/StashNotifier.java
> +			boolean disableAbortAsFailures,
I guess we should change it in all the other places as well ;-)

2017-05-12 10:09 UTC, lucamilanesio commented on src/main/java/org/jenkinsci/plugins/stashNotifier/StashNotifier.java
> +		} else if (buildResult == Result.ABORTED && (disableAbortAsFailures || disableInProgress)) {
Hold on, if we disable the in progress *and* the build has just being canceled, why should we mark it as failed after all?
On the other side you are right, if we started saying that the build is in progress *and* has been canceled, we have to tell Stash somehow.

Does this mean that we do not need any disableAbortAsFailure *and* we just notify the abort only if we informed Stash that the build was in progress?

2017-05-12 10:14 UTC, scaytrase commented on src/main/java/org/jenkinsci/plugins/stashNotifier/StashNotifier.java
> +		} else if (buildResult == Result.ABORTED && (disableAbortAsFailures || disableInProgress)) {
> why should we mark it as failed after all

Sounds reasonable. I it is equal to disable inprogress indeed

2017-05-15 10:51 UTC, lucamilanesio commented on src/main/java/org/jenkinsci/plugins/stashNotifier/StashNotifier.java
> +		} else if (buildResult == Result.ABORTED && (disableAbortAsFailures || disableInProgress)) {
Done, just removed the flag and used the current inprogress configuration.

2017-05-16 06:34 UTC, scaytrase approved these changes
Generally looks OK, I'll test and merge is as soon as I can

2017-05-17 08:36 UTC, lucamilanesio commented
@scaytrase did you have any time to do a smoke test yourself? We already use it here in production and works :-)

2017-06-02 13:39 UTC, merged

2017-08-15 09:53 UTC, danmademe commented
I seem to be missing the `considerUnstableAsSuccess` setting in jenkins config.

has something gone wrong?